// <auto-generated />
namespace community_house.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class addedfavouritesandmore : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedfavouritesandmore));
        
        string IMigrationMetadata.Id
        {
            get { return "201412171455262_added-favourites-and-more"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
